common/models/Book.php
<?php

namespace common\models;
use common\traits\StatusTrait;
use Yii;

/**
 * This is the model class for table "book".
 *
 * @property int $id
 * @property string $name
 * @property int $year
 * @property int $pages
 * @property string $genre
 * @property int $author_id
 *
 * @property Author $author
 */
class Book extends \yii\db\ActiveRecord
{
    use StatusTrait;
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'book';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['name', 'year', 'pages', 'genre', 'author_id'], 'required'],
            [['year', 'pages', 'author_id'], 'integer'],
            [['name', 'genre'], 'string', 'max' => 255],
            [['author_id'], 'exist', 'skipOnError' => true, 'targetClass' => Author::className(), 'targetAttribute' => ['author_id' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('admin', 'ID'),
            'name' => Yii::t('admin', 'Name'),
            'year' => Yii::t('admin', 'Year'),
            'pages' => Yii::t('admin', 'Pages'),
            'genre' => Yii::t('admin', 'Genre'),
            'author_id' => Yii::t('admin', 'Author ID'),
        ];
    }

    public static function getAuthorsList()
    {
        return $authors = Author::findAll(['status' => Author::getActiveStatus()]);
    }

    public static function getAuthorName($id)
    {
        return Author::findOne(['id'=> $id])->name;
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAuthor()
    {
        return $this->hasOne(Author::class, ['id' => 'author_id']);
    }
}

backend/controllers/AuthorController.php
<?php

namespace backend\controllers;

use Yii;
use common\models\Author;
use common\models\search\AuthorSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * AuthorController implements the CRUD actions for Author model.
 */
class AuthorController extends SiteController
{
    /**
     * Lists all Author models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new AuthorSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Author model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Author model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Author();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Author model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Author model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Author model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Author the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Author::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

backend/controllers/BookController.php
<?php

namespace backend\controllers;

use common\models\Author;
use Yii;
use common\models\Book;
use common\models\search\BookSearch;
use yii\helpers\ArrayHelper;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * BookController implements the CRUD actions for Book model.
 */
class BookController extends SiteController
{

    /**
     * Lists all Book models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new BookSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Book model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Book model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {

        $book = new Book();
        $authors = ArrayHelper::map(Book::getAuthorsList(), 'id', 'name');
        if ($this->isAuthors()) {
//            var_dump($book->load(Yii::$app->request->post()));
            if ($book->load(Yii::$app->request->post()) && $book->save()) {
                return $this->redirect(['view', 'id' => $book->id]);
            } else {
                return $this->render('create', [
                    'data' => $authors,
                    'book' => $book,
                ]);
            }
        }
        Yii::$app->session->setFlash('no authors', 'You must create author before book.');
        return $this->render('create', [
            'data' => $authors,
            'book' => $book,
        ]);



    }

    /**
     * Updates an existing Book model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionUpdate($id)
    {
        $book = $this->findModel($id);
        $author = Book::getAuthorsList();

        if ($book->load(Yii::$app->request->post()) && $book->save()) {
            return $this->redirect(['view', 'id' => $book->id]);
        } else {
            return $this->render('update', [
                'book' => $book,
                'author' => $author,
            ]);
        }
    }

    /**
     * Deletes an existing Book model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the Book model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Book the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Book::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    protected function isAuthors()
    {
        $authors = Book::getAuthorsList();
        if ($authors) {
            return true;
        }
        return false;
    }
}

backend/views/book/_form.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $book common\models\Book */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="book-form box box-primary">
    <?php $form = ActiveForm::begin(); ?>
    <div class="box-body table-responsive">

        <?= $form->field($book, 'name')->textInput(['maxlength' => true]) ?>

        <?= $form->field($book, 'pages')->widget(\kartik\select2\Select2::class, [
            'data' => range(0, 1500),
            'options' => ['placeholder' => Yii::t('admin', 'Select number of pages')],
            'pluginOptions' => [
                'allowClear' => true
            ],
        ]) ?>
        <?= $form->field($book, 'year')->widget(\kartik\select2\Select2::class, [
            'data' => range(0, date('Y')),
            'options' => ['placeholder' => Yii::t('admin', 'Select year')],
            'pluginOptions' => [
                'allowClear' => true
            ],
        ]) ?>

        <?= $form->field($book, 'genre')->textInput(['maxlength' => true]) ?>

        <?= $form->field($book, 'author_id')->widget(\kartik\select2\Select2::class, [
            'data' => $data,
            'language' => Yii::$app->language,
            'options' => ['placeholder' => Yii::t('admin', 'Select an author')],
            'pluginOptions' => [
                    'default',
                'allowClear' => true
            ],
        ]); ?>
        <?= $form->field($book, 'status')->dropDownList(\common\models\Book::statusList()) ?>

    </div>
    <div class="box-footer">
        <?= Html::submitButton(Yii::t('admin', 'Save'), ['class' => 'btn btn-success btn-flat']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

backend/views/book/_form_update.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\helpers\ArrayHelper;

/* @var $this yii\web\View */
/* @var $book common\models\Book */
/* @var $author common\models\Author[] */
/* @var $form yii\widgets\ActiveForm */
?>
<div class="book-form box box-primary">
    <?php $form = ActiveForm::begin(); ?>
    <div class="box-body table-responsive">

        <?= $form->field($book, 'name')->textInput(['maxlength' => true]) ?>

        <?= $form->field($book, 'pages')->textInput();?>
        <?= $form->field($book, 'year')->textInput();?>

        <?= $form->field($book, 'genre')->textInput(['maxlength' => true]) ?>

        <?= $form->field($book, 'author_id')->dropDownList(ArrayHelper::map($author, 'id','name')) ?>
        <?= $form->field($book, 'status')->dropDownList(\common\models\Book::statusList()) ?>

    </div>
    <div class="box-footer">
        <?= Html::submitButton(Yii::t('admin', 'Save'), ['class' => 'btn btn-success btn-flat']) ?>
    </div>
    <?php ActiveForm::end(); ?>
</div>

backend/views/book/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model common\models\search\BookSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="book-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'name') ?>

    <?= $form->field($model, 'year') ?>

    <?= $form->field($model, 'pages') ?>

    <?= $form->field($model, 'genre') ?>

    <?php // echo $form->field($model, 'author_id') ?>

    <div class="form-group">
        <?= Html::submitButton(Yii::t('admin', 'Search'), ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton(Yii::t('admin', 'Reset'), ['class' => 'btn btn-default']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/book/create.php
<?php

use yii\helpers\Html;


/* @var $this yii\web\View */
/* @var $book common\models\Book */

$this->title = Yii::t('admin', 'Create Book');
$this->params['breadcrumbs'][] = ['label' => Yii::t('admin', 'Books'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="book-create">
    <? if (!Yii::$app->session->hasFlash('no authors')): ?>
        <?= $this->render('_form', [
            'data' => $data,
            'book' => $book,
        ]) ?>
    <? else: ?>
        <div class="alert alert-warning alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span
                        aria-hidden="true">&times;</span></button>
            <?= Yii::$app->session->getFlash('no authors') ?><?php echo Yii::$app->session->getFlash('success'); ?>
        </div>

        <div class="box-header with-border">
            <?= Html::a(Yii::t('admin', 'Create Author'), ['author/create'], ['class' => 'btn btn-success btn-flat']) ?>
        </div>
    <? endif; ?>

</div>

backend/views/book/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $searchModel common\models\search\BookSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = Yii::t('admin', 'Books');
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="book-index box box-primary">
    <div class="box-header with-border">
        <?= Html::a(Yii::t('admin', 'Create Book'), ['create'], ['class' => 'btn btn-success btn-flat']) ?>
    </div>
    <div class="box-body table-responsive no-padding">
        <?php // echo $this->render('_search', ['model' => $searchModel]); ?>
        <?= GridView::widget([
            'dataProvider' => $dataProvider,
            'filterModel' => $searchModel,
            'layout' => "{items}\n{summary}\n{pager}",
            'columns' => [
                ['class' => 'yii\grid\SerialColumn'],

                'id',
                'name',
                'year',
                'pages',
                'genre',
                // 'author_id',

                ['class' => 'yii\grid\ActionColumn'],
            ],
        ]); ?>
    </div>
</div>

backend/views/book/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $book common\models\Book */
/* @var $author common\models\Author */

$this->title = Yii::t('admin', 'Update {modelClass}: ', [
    'modelClass' => 'Book',
]) . $book->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('admin', 'Books'), 'url' => ['index']];
$this->params['breadcrumbs'][] = ['label' => $book->name, 'url' => ['view', 'id' => $book->id]];
$this->params['breadcrumbs'][] = Yii::t('admin', 'Update');
?>
<div class="book-update">

    <?= $this->render('_form_update', [
        'book' => $book,
        'author' => $author,
    ]) ?>

</div>

backend/views/book/view.php
<?php

use yii\helpers\Html;
use yii\widgets\DetailView;

/* @var $this yii\web\View */
/* @var $model common\models\Book */

$this->title = $model->name;
$this->params['breadcrumbs'][] = ['label' => Yii::t('admin', 'Books'), 'url' => ['index']];
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="book-view box box-primary">
    <div class="box-header">
        <?= Html::a(Yii::t('admin', 'Update'), ['update', 'id' => $model->id], ['class' => 'btn btn-primary btn-flat']) ?>
        <?= Html::a(Yii::t('admin', 'Delete'), ['delete', 'id' => $model->id], [
            'class' => 'btn btn-danger btn-flat',
            'data' => [
                'confirm' => Yii::t('admin', 'Are you sure you want to delete this item?'),
                'method' => 'post',
            ],
        ]) ?>
    </div>
    <div class="box-body table-responsive no-padding">
        <?= DetailView::widget([
            'model' => $model,
            'attributes' => [
                'id',
                'name',
                'year',
                'pages',
                'genre',
                ['label' => Yii::t('admin', 'Author'),
                    'value' => function ($model) {
                        return \common\models\Book::getAuthorName($model->author_id);
                    }
                ],
                'status'
            ],
        ]) ?>
    </div>
</div>